const val springBootVersion = "3.3.4"
const val vavrVersion = "1.0.0-alpha-4"
const val lombokVersion = "1.18.34"
const val mapstructVersion = "1.5.5.Final"
const val lombokMapstructBindingVersion = "0.2.0"